- name: Install Backend Dependencies
  run: |
    cd CI-PROJECT/server
    npm install

- name: Run Backend Tests
  run: |
    cd CI-PROJECT/server
    npm test

- name: Install Frontend Dependencies
  run: |
    cd CI-PROJECT/client
    npm install

- name: Build React App
  run: |
    cd CI-PROJECT/client
    npm run build