name: MERN CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Show repository structure
        run: |
          pwd
          ls -R

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Backend Dependencies
        run: |
          cd server
          npm install

      - name: Run Backend Tests
        run: |
          cd server
          npm test

      - name: Install Frontend Dependencies
        run: |
          cd client
          npm install

      - name: Build React App
        run: |
          cd client
          npm run build